### ISSUE TITLE
.africa extensions not supported.

### ISSUE THREAD

**Issue by digitalyeast** [eithan1231/whois-light#1]
.africa extensions returning error.

**Comment by eithan1231** [comment]
Thanks for reporting this issue.

The index of whois servers have been updated as-per iana.org's root list.

You can see the commit here https://github.com/eithan1231/whois-light/commit/898b7bf2b5df545f17143f1a03e793c744e697da

Be sure to run `npm install whois-light` to update this package, changes will come into affect once you do.
