### ISSUE TITLE
Format option doesn't work for some TLDs

### ISSUE THREAD

**Issue by ipmanlk** [eithan1231/whois-light#3]
**Describe the bug**  
There is an issue with parsing raw whois string in some TLDs such as .ru.

**To Reproduce**
Try to resolve whois information for ``yandex.ru`` domain with format option set to true.

**Module version**  
v1.1.4

**Comment by eithan1231** [comment]
This issue appears to be a result of the .ru master server not following the outlines of rfc3912 in regards to line breaks. I have added in a fix which will hopefully rectify this issue.

Please let me know if you spot any further issues.

Package version 1.1.5 has been published.
