### ISSUE TITLE
Unable to resolve tld .xyz

### ISSUE THREAD

**Issue by nenkoszai** [eithan1231/whois-light#5]
cannot do lookup on any .xyz domains. 
As it lead to server timeout

**Comment by eithan1231** [comment]
Hi,

Thanks for reporting this issue. I will investigate as soon as possible.

Please let us know if you experience any further issues.

**Comment by eithan1231** [comment]
We have reviewed this issue and it appears to have the most recent domain information.

Can you please ensure you're upgraded to the latest version of `whois-light`?
